#ifndef HACCABANA_CORE_CONFIG_HPP
#define HACCABANA_CORE_CONFIG_HPP

#define HACCabana_VERSION_STRING "@PROJECT_VERSION@"

#define HACCabana_GIT_COMMIT_HASH "@HACCabana_GIT_COMMIT_HASH@"

#cmakedefine HACCabana_ENABLE_CANOPY

#endif // HACCABANA_CORE_CONFIG_HPP